android.useAndroidX=true
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m
systemProp.gradle.user.home=f:/cache/gradle
org.gradle.configuration-cache=true
org.gradle.daemon.idletimeout=120000
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.worker.max=3

kotlin.parallel.tasks.in.project=true

RELEASE_STORE_PASSWORD=[PASSWORD]
RELEASE_KEY_ALIAS=your_key
RELEASE_KEY_PASSWORD=[PASSWORD]

